definitions:
  caches:
    bundler: ./vendor

  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: new_build_test
        POSTGRES_USER: root
        POSTGRES_HOST_AUTH_METHOD: trust
    redis:
      image: redis

  steps:
    - step: &app_build
        name: NEW BUILD
        image: ruby:3.0.3
        caches:
          - bundler

        script:
          - apt-get update && apt-get install -y libpq-dev poppler-utils libdmtx-dev libvips42 postgresql postgresql-contrib
          - gem install bundler -v 2.2.33
          - bundle config gems.selise.tech ${GEM_USERNAME}:${GEM_PASSWORD}
          - bundle _2.2.33_ install
          - RAILS_ENV=test bundle exec rails db:test:prepare; rails assets:precompile
          - bundle audit
          - bundler leak update
          - bundle leak
          - bundle exec rspec --tag ~@ips; rubocop
          - brakeman; rubycritic
          - bundle exec rails_best_practices

        services:.33_ install
          - postgres
          - redis

    - step: &docker_staging_build
        name: Docker Build & Deploy
        caches:
          - docker
        services:
          - docker
        script:
          - BITBUCKET_TAG=${BITBUCKET_TAG#*/}
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build --build-arg RAILS_MASTER_KEY=$RAILS_STAGING_MASTER_KEY
            --build-arg GEM_USERNAME=$GEM_USERNAME
            --build-arg GEM_PASSWORD=$GEM_PASSWORD
            --build-arg ALLOWED_DOMAINS=$ALLOWED_DOMAINS
            -t selisebt/new-build:${BITBUCKET_TAG} .

          - docker push selisebt/new-build:${BITBUCKET_TAG}

    - step: &docker_production_build
        name: Docker Build & Deploy
        caches:
          - docker
        services:
          - docker
        script:
          - BITBUCKET_TAG=${BITBUCKET_TAG#*/}
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build --build-arg RAILS_MASTER_KEY=$RAILS_PROD_MASTER_KEY
            --build-arg GEM_USERNAME=$GEM_USERNAME
            --build-arg GEM_PASSWORD=$GEM_PASSWORD
            --build-arg ALLOWED_DOMAINS=$ALLOWED_DOMAINS
            -t selisebt/new-build:${BITBUCKET_TAG} .

          - docker push selisebt/new-build:${BITBUCKET_TAG}

pipelines:
  pull-requests:
    '**':
      - step: *app_build
  custom:
    staging:
      - variables:
        - name: BITBUCKET_TAG
      - step: *docker_staging_build
    production:
      - variables:
          - name: BITBUCKET_TAG
      - step: *docker_production_build
