definitions:
  caches:
    bundler: ./vendor

  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: new_build_test
        POSTGRES_USER: root
        POSTGRES_HOST_AUTH_METHOD: trust

  steps:
    - step: &app_build
        name: NEW BUILD
        image: ruby:3.0.1
        caches:
          - bundler

        script:
          - apt-get update && apt-get install -y libpq-dev poppler-utils libdmtx-dev libvips42
          - gem install bundler -v 2.2.14
          - bundle config gems.selise.tech ${GEM_USERNAME}:${GEM_PASSWORD}
          - bundle _2.2.14_ install
          - RAILS_ENV=test bundle exec rails db:create db:schema:load
          - bundle audit
          - bundle exec rspec; rubocop
          - LOCALE=de bundle exec rspec
          - LOCALE=fr bundle exec rspec
          - LOCALE=it bundle exec rspec
          - brakeman; bullet; rubycritic
          - bundle exec rails_best_practices

        services:
          - postgres

pipelines:
  pull-requests:
    '**':
      - step: *app_build