definitions:
  caches:
    bundler: ./vendor

  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: new_build_test
        POSTGRES_USER: root
        POSTGRES_HOST_AUTH_METHOD: trust
    redis:
      image: redis

  steps:
    - step: &app_build
        name: NEW BUILD
        image: ruby:3.0.1
        caches:
          - bundler

        script:
          - apt-get update && apt-get install -y libpq-dev poppler-utils libdmtx-dev libvips42 postgresql postgresql-contrib
          - gem install bundler -v 2.2.14
          - bundle config gems.selise.tech ${GEM_USERNAME}:${GEM_PASSWORD}
          - bundle _2.2.14_ install
          - RAILS_ENV=test bundle exec rails db:test:prepare; rails assets:precompile
          - bundle audit
          - bundle exec rspec --tag ~@ips; rubocop
          - LOCALE=de bundle exec rspec --tag ~@ips
          - LOCALE=fr bundle exec rspec --tag ~@ips
          - LOCALE=it bundle exec rspec --tag ~@ips
          - brakeman; rubycritic
          - bundle exec rails_best_practices

        services:
          - postgres
          - redis

    - step: &docker_build
        name: Docker Build & Deploy
        caches:
          - docker
        services:
          - docker
        script:
          - BITBUCKET_TAG=${BITBUCKET_TAG#*/}
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
            --build-arg DEVISE_SECRET_KEY=$DEVISE_SECRET_KEY
            --build-arg DEVISE_JWT_SECRET_KEY=$DEVISE_JWT_SECRET_KEY
            --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY
            --build-arg GEM_USERNAME=$GEM_USERNAME
            --build-arg GEM_PASSWORD=$GEM_PASSWORD
            --build-arg ALLOWED_DOMAINS=$ALLOWED_DOMAINS
            -t selisebt/new-build:${BITBUCKET_TAG} .

          - docker push selisebt/new-build:${BITBUCKET_TAG}

pipelines:
  pull-requests:
    '**':
      - step: *app_build
  custom:
    be:
      - variables:
        - name: BITBUCKET_TAG
      - step: *docker_build
