admin_toolkit:
  recipient:
    kam_investor_created:
      - owner_email
      - investor_id
    kam_investor_updated:
      - owner_email
    kam_investor_deleted:
      - owner_email
      - investor_id

  owner:
    competition_created:
      - name
    competition_updated:
      - name
    competition_deleted:
      - name
    kam_investor_created:
      - recipient_email
      - investor_id
    kam_investor_updated:
      - recipient_email
    kam_investor_deleted:
      - recipient_email
      - investor_id
    kam_region_updated:
      - trackable_id
    penetration_created:
      - zip
    penetration_updated:
      - zip
    penetration_deleted:
      - zip
    footprint_building_updated:
      - max
    footprint_value_updated:
      - trackable_id
    label_group_updated:
      - trackable_name
      - labelList
    pct_cost_updated:
      - max
    pct_month_updated:
      - max
    pct_value_updated:
      - trackable_id
    project_cost_updated:
      - standard

  others:
    competition_created:
      - owner_email
      - name
    competition_updated:
      - owner_email
      - name
    competition_deleted:
      - owner_email
      - name
    kam_investor_created:
      - owner_email
      - recipient_email
      - investor_id
    kam_investor_updated:
      - owner_email
      - recipient_email
    kam_investor_deleted:
      - owner_email
      - investor_id
      - recipient_email
    kam_region_updated:
      - owner_email
    penetration_created:
      - owner_email
      - zip
    penetration_updated:
      - owner_email
      - zip
    penetration_deleted:
      - owner_email
      - zip
    footprint_building_updated:
      - owner_email
      - max
    footprint_value_updated:
      - owner_email
    label_group_updated:
      - owner_email
      - trackable_name
      - labelList
    pct_cost_updated:
      - owner_email
      - max
    pct_month_updated:
      - owner_email
      - max
    pct_value_updated:
      - owner_email
    project_cost_updated:
      - owner_email
      - standard
