project:
  recipient:
  owner:
    project_created:
      - project_name
    project_updated:
      - project_name
      - status
    project_draft_version:
      - project_name
    incharge_updated:
      - incharge_email
      - project_name
    project_pct_cost:
      - parameters
    file_uploaded:
      - filename
    technical_analysis:
      - project_name
      - status
    technical_analysis_completed:
      - project_name
      - status
    ready_for_offer:
      - previous_status
      - project_name
      - status
    archived:
      - previous_status
      - project_name
    reverted:
      - owner_email
      - previous_status
      - project_name
      - status
  others:
    project_created:
      - project_name
      - owner_email
      - entry_type
    project_updated:
      - project_name
      - status
      - owner_email
    project_draft_version:
      - project_name
      - owner_email
    incharge_updated:
      - owner_email
      - incharge_email
      - project_name
    file_uploaded:
      - owner_email
      - filename
    technical_analysis:
      - owner_email
      - project_name
      - status
    technical_analysis_completed:
      - owner_email
      - project_name
      - status
    ready_for_offer:
      - owner_email
      - previous_status
      - project_name
      - status
    archived:
      - owner_email
      - previous_status
      - project_name
    reverted:
      - owner_email
      - previous_status
      - project_name
      - status
projects:
  recipient:
    task_created:
      - owner_email
      - title
      - copy
    task_deleted:
      - owner_email
      - type
      - title
    task_updated:
      - owner_email
      - previous_status
      - status
      - type
      - title
  owner:
    address_book_created:
      - project_name
      - role_type
    address_book_updated:
      - project_name
      - role_type
    building_created:
      - project_name
      - name
    building_deleted:
      - project_name
      - name
    building_updated:
      - project_name
      - name
    building_imported:
      - filename
    labels_created:
      - label_list
      - project_name
      - status
    labels_updated:
      - label_list
      - project_name
      - status
    task_created:
      - recipient_email
      - title
      - copy
    task_deleted:
      - recipient_email
      - type
      - title
    task_updated:
      - recipient_email
      - previous_status
      - status
      - type
      - title
    payback_period_updated:
      - project_name
    project_imported:
      - filename
    file_uploaded:
      - filename
  others:
    address_book_created:
      - project_name
      - role_type
      - owner_email
    address_book_updated:
      - project_name
      - role_type
      - owner_email
    building_created:
      - project_name
      - name
      - owner_email
    building_deleted:
      - project_name
      - name
      - owner_email
    building_updated:
      - project_name
      - name
      - owner_email
    building_imported:
      - filename
      - owner_email
    labels_created:
      - label_list
      - project_name
      - status
      - owner_email
    labels_updated:
      - label_list
      - project_name
      - status
      - owner_email
    task_created:
      - title
      - copy
      - owner_email
      - recipient_email
    task_deleted:
      - owner_email
      - type
      - title
      - recipient_email
    task_updated:
      - recipient_email
      - owner_email
      - previous_status
      - status
      - type
      - title
    payback_period_updated:
      - project_name
      - owner_email
    project_imported:
      - filename
      - owner_email
    file_uploaded:
      - owner_email
      - filename

active_storage:
  owner:
    attachment_file_deleted:
      - filename
      - type
    attachment_file_updated:
      - filename
      - type
      - owner_email
  others:
    attachment_file_deleted:
      - filename
      - type
      - owner_email
    attachment_file_updated:
      - filename
      - type
      - owner_email
