project:
  recipient:
  owner:
    project_created:
      - project_name
    project_updated:
      - project_name
      - status
    project_draft_version:
      - project_name
    project_category_updated:
      - parameters
    incharge_updated:
      - parameters
    project_pct_cost:
      - parameters
    file_uploaded:
      - name
    technical_analysis:
      - project_name
      - status
    technical_analysis_completed:
      - project_name
      - status
    ready_for_offer:
      - previous_status
      - project_name
      - status
    archived:
      - previous_status
      - project_name
    reverted:
      - owner_email
      - previous_status
      - project_name
      - status
  others:
    project_created:
      - project_name
      - owner_email
      - entry_type
    project_updated:
      - project_name
      - status
      - owner_email
    project_draft_version:
      - project_name
      - owner_email
    incharge_updated:
      - parameters
    file_uploaded:
      - owner_email
      - name
    technical_analysis:
      - owner_email
      - project_name
      - status
    technical_analysis_completed:
      - owner_email
      - project_name
      - status
    ready_for_offer:
      - owner_email
      - previous_status
      - project_name
      - status
    archived:
      - owner_email
      - previous_status
      - project_name
    reverted:
      - owner_email
      - previous_status
      - project_name
      - status
projects:
  recipient:
    project_task_created:
      - project_name
      - owner_email
      - title
    project_task_deleted:
      - parameters
    project_task_updated:
      - parameters
    task_created:
      - parameters
    task_deleted:
      - parameters
    task_updated:
      - parameters
  owner:
    address_book_created:
      - project_name
      - role_type
    address_book_updated:
      - project_name
      - role_type
    building_created:
      - project_name
      - name
    building_deleted:
      - project_name
      - name
    building_updated:
      - project_name
      - name
    building_imported:
      - filename
    labels_created:
      - parameters
    labels_updated:
      - parameters
    task_created:
      - recipient_email
      - title
    task_deleted:
      - parameters
    task_updated:
      - parameters
    payback_period_updated:
      - project_name
    project_imported:
      - filename
  others:
    address_book_created:
      - project_name
      - role_type
      - owner_email
    address_book_updated:
      - project_name
      - role_type
      - owner_email
    building_created:
      - project_name
      - name
      - owner_email
    building_deleted:
      - project_name
      - name
      - owner_email
    building_updated:
      - project_name
      - name
      - owner_email
    building_imported:
      - filename
      - owner_email
    labels_created:
      - parameters
    labels_updated:
      - parameters
    task_created:
      - owner_email
      - recipient_email
      - title
    task_deleted:
      - parameters
    task_updated:
      - parameters
    payback_period_updated:
      - project_name
      - owner_email
    project_imported:
      - filename
      - owner_email

active_storage:
  owner:
    attachment_file_deleted:
      - parameters
    attachment_file_updated:
      - parameters
  others:
    attachment_file_deleted:
      - owner_email
    attachment_file_updated:
      - parameters
