telco/uam/user:
  - status_updated
  - user_invited
  - user_reinvited
  - profile_updated
  - profile_deleted
  - role_updated

admin_toolkit/competition:
  - competition_created
  - competition_updated
  - competition_deleted

admin_toolkit/kam_investor:
  - kam_investor_created
  - kam_investor_updated
  - kam_investor_deleted

admin_toolkit/kam_region:
  - kam_region_updated

admin_toolkit/penetration:
  - penetration_created
  - penetration_updated
  - penetration_deleted

admin_toolkit/footprint_building:
  - footprint_building_updated

admin_toolkit/footprint_value:
  - footprint_value_updated

admin_toolkit/label_group:
  - label_group_updated

admin_toolkit/pct_cost:
  - pct_cost_updated

admin_toolkit/pct_month:
  - pct_month_updated

admin_toolkit/pct_value:
  - pct_value_updated

admin_toolkit/project_cost:
  - project_cost_updated

project:
  - project_created
  - project_updated
  - project_draft_version
  - project_category_updated
  - incharge_updated
  - file_uploaded
projects/address_book:
  - address_book_created
  - address_book_updated
projects/building:
  - building_created
  - building_deleted
  - building_updated
projects/label_group:
  - label_group_created
  - label_group_updated
projects/task:
  - task_created
  - task_deleted
  - task_updated
projects/pct_cost:
  - payback_period_updated
active_storage/attachment:
  - attachment_file_deleted
  - attachment_file_updated
