user:
  - read
  - invite
  - update
  - update_role
  - update_status
  - delete
role:
  - read
project:
  - read
  - create
  - update

  - open
  - technical_analysis
  - ready_for_offer
  - complex
  - archive
  - gt_10_000