- West Bern-Seeland
- Ost SG-TG-AR-AI
- Ticino
- Ost GR und ZH Oberland
- Romandie
- West Zentralschweiz + Solothurn
- Ost ZH
- West AG-BL-BS
- Ost Agglomeration Winterthur
- Romandie Offnet
- Ost GR und ZH Oberland Offnet
- West Zentralschweiz + Solothurn Offnet
- Ost SG-TG-AR-AI Offnet
- Ticino Offnet
- West AG-BL-BS Offnet
- West Bern-Seeland Offnet
- Ost ZH Offnet
- Romandie-Oberwallis Offnet
