super_user: # role
  user: # module
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read

administrator:
  user:
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read
