super_user:
  user:
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read
  project:
    - read
    - create
    - update
    - delete

    - technical_analysis
    - ready_for_offer
    - archive
    - complex
    - gt_10_000

administrator:
  user:
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read
  project:
    - read
    - create
    - update

    - technical_analysis
    - complex
    - archive

team_expert:
  user:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis

team_standard:
  user:
    - read
  project:
    - read
    - create
    - update
management:
  user:
    - read
  project:
    - read
    - create
    - update

    - technical_analysis
    - ready_for_offer
    - gt_10_000

presales:
  user:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - complex

manager_presales:
  user:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - ready_for_offer
    - complex

manager_nbo_kam:
  user:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - ready_for_offer

kam:
  user:
    - read
  project:
    - read
    - create
    - update

manager_commercialization:
  user:
    - read
  project:
    - read