super_user:
  user:
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read
  project:
    - read
    - create
    - update
    - import
    - delete
    - confirm

    - technical_analysis
    - ready_for_offer
    - offer_confirmation
    - archive
    - complex
    - build_cost_exceeding

administrator:
  user:
    - read
    - invite
    - update
    - update_role
    - update_status
    - delete
  role:
    - read
  project:
    - read
    - create
    - update
    - import

    - technical_analysis
    - complex
    - archive

team_expert:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - ready_for_offer
    - offer_confirmation
    - archive

team_standard:
  user:
    - read
  project:
    - read
    - create
    - update
    - archive
    - confirm
    - ready_for_offer
    - offer_confirmation
management:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - import
    - confirm

    - technical_analysis
    - ready_for_offer
    - offer_confirmation
    - build_cost_exceeding
    - archive

presales:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - complex
    - archive
    - ready_for_offer
    - offer_confirmation
manager_presales:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - ready_for_offer
    - offer_confirmation
    - complex
    - archive

manager_nbo_kam:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - technical_analysis
    - ready_for_offer
    - offer_confirmation
    - archive

kam:
  user:
    - read
  role:
    - read
  project:
    - read
    - create
    - update
    - archive
    - ready_for_offer
    - offer_confirmation
    - confirm

manager_commercialization:
  user:
    - read
  project:
    - read
    - archive