test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

microsoft:
  service: AzureStorage
  storage_account_name: <%= Rails.application.credentials.dig(:azure_storage, :storage_account_name) %>
  storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
  container: <%= Rails.application.credentials.dig(:azure_storage, :container) %>
